### ISSUE TITLE
Migration from Theme UI

### ISSUE THREAD

**Issue by kripod** [kripod/glaze#23]
## Motivation

The ecosystem behind Theme UI is growing fast. It'd be great to have a converter available for their own theme format. Also, a detailed documentation page which compares the differences between theme specs would also be very useful.

## Basic example

```js
/* theme.treat.js */

import { createTheme, fromThemeUI } from 'glaze';

export default createTheme(fromThemeUI({
  // Theme UI tokens, e.g.:
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#07c',
    secondary: '#05a',
    accent: '#609',
    muted: '#f6f6f6',
  },
  fonts: {
    body: 'system-ui, sans-serif',
    heading: 'system-ui, sans-serif',
    monospace: 'Menlo, monospace',
  },
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
}));
```

This would even allow using existing Theme UI presets, e.g.:

```js
/* theme.treat.js */

import { bootstrap } from '@theme-ui/presets'
import { createTheme, fromThemeUI } from 'glaze';

export default createTheme(fromThemeUI({
  ...bootstrap,
  colors: {
    ...bootstrap.colors,
    brand: '#123456',
  },
}));
```

**Comment by hennessyevan** [comment]
I’d be willing to take a stab at this.

**Comment by kripod** [comment]
Fantastic, thank you!

As you can see, quite a few of Theme UI's theming approaches are not supported yet (e.g. color schemes, see #7) and component variants. For those keys, I would suggest showing an aggregated console warning during development with `isDev` and `warnOnce`, instructing the developer to comment out the nonconvertible rules.

I think this should be a function put inside `packages/glaze/src/theme.ts`, under the name `fromThemeUI`, just after the definition of `createTheme`. Please export it from `src/index.ts` as well!

**Comment by hennessyevan** [comment]
#### A few things as I jump into this

1. For unsupported tokens (color modes, variants) we could just ignore them and warn? I don't know that it would be strictly necessary to have the dev comment out tokens that aren't going to be picked up by glaze anyways, especially if the goal is to support these tokens eventually.
2. Some of glaze's theme spec seems to conflict with theme-ui's
   - breakpoints in theme-ui can be strings to support `em`, `rem`, `%`, etc. Glaze (treat here) seems to only support numbers?

**Comment by kripod** [comment]
> 
> #### A few things as I jump into this
> 
>     1. For unsupported tokens (color modes, variants) we could just ignore them and warn? I don't know that it would be strictly necessary to have the dev comment out tokens that aren't going to be picked up by glaze anyways, especially if the goal is to support these tokens eventually.
> 
>     2. Some of glaze's theme spec seems to conflict with theme-ui's
>        
>        * breakpoints in theme-ui can be strings to support `em`, `rem`, `%`, etc. Glaze (treat here) seems to only support numbers?

1. Good idea, a warning should be sufficient for now.
2. I'm not yet sure about supporting string-based keys. Personally, I don't think that devices can be categorized based on screen width (e.g. associating sizes with `mobile`, `tablet`, `desktop` and so on). Please discuss about this in greater depth at #3. Until then, I would recommend an automatic conversion based on `Object.values(themeUITokens.breakpoints).sort()` and showing a warning about it on the console when it happens, suggesting to rewrite `breakpoints` into the auto-converted value, which gets printed to the console during development.

**Comment by hennessyevan** [comment]
Ahhh.. yeah for the breakpoints I meant more like [Theme UI supports and encourages strings](https://theme-ui.com/theme-spec#breakpoints) as in 
```ts
const themeUI = {
  // ...
  breakpoints: ['20em', '10%', '768px']
}
```
My approach thus far has been to
1. accept numbers
2. strip `px` and use those numbers
3. warn about other CSS lengths and leave `undefined` in their place so as to leave the index in tact as much as possible. The above example would become

```ts
const themeUI = {
  // ...
  breakpoints: ['20em', '10%', '768px']
}
fromThemeUI(themeUI) // { breakpoints: [undefined, undefined, 768] }
```

**Comment by kripod** [comment]
Sorry, I totally misunderstood you last time. I thought the discussion was about formats like `breakpoints: { mobile: 600, tablet: 800, desktop: 1000 }`.

As for strings, I think that `em` and `rem` should be matched and converted into a `* 16` multiplier while emitting a warning about the conversion and its potential side-effects. E.g. `'20em' -> 20 * 16 -> 320`. For any other string-based values, an error should be shown (not just a warning).

I lean towards pixel-based media queries because of the reasons in [Adam Wathan's article about the topic](https://adamwathan.me/dont-use-em-for-media-queries/). It's an interesting read, I can only recommend it.

**Comment by hennessyevan** [comment]
Yeah, I've never personally used anything other than pixels. That all makes the kind of sense that does 👍 I'll get a draft PR going.
