### ISSUE TITLE
Warn during development when breakpoints are not ordered

### ISSUE THREAD

**Issue by kripod** [kripod/glaze#25]
## Motivation

According to the explanation of @christianalfoni in the [_Sorry to see you go Classy-UI, hello Stitches!_ video (13:45–14:20)](https://youtu.be/EhM8XxaoPnc?t=825), media queries need to be in order to solve issues with CSS specificity.

## Details

In [`createTheme(tokens)`](https://github.com/kripod/glaze/blob/de97e10e3c4ba6c71c032dafad18a58b634c499b/packages/glaze/src/theme.ts#L49-L60), call [`warnOnce()`](https://github.com/kripod/glaze/blob/de97e10e3c4ba6c71c032dafad18a58b634c499b/packages/glaze/src/logger.ts#L19) when `tokens.breakpoints` are not in increasing order [during development](https://github.com/kripod/glaze/blob/de97e10e3c4ba6c71c032dafad18a58b634c499b/packages/glaze/src/env.ts#L2).

**Comment by hennessyevan** [comment]
I’ll take a stab at this today or tomorrow

**Comment by kripod** [comment]
@hennessyevan Awesome, thank you! 🙌
