### ISSUE TITLE
Clarify React dependency

### ISSUE THREAD

**Issue by bnjm** [kripod/glaze#26]
Hi, this looks like a really interesting project which combines the best of different css-in-js frameworks. I had trouble understanding whether React is required or whether it can be used with other frameworks, I think it would be helpful to clarify this somewhere. 

Some inspiration from the emotion docs:

In the emotion package docs 
> The emotion package is framework agnostic and the simplest way to use Emotion.

In the emotion/core page docs
> The “@emotion/core” package requires React and is recommended for users of that framework if possible.

**Comment by kripod** [comment]
Good observation, thank you! I would appreciate if you could help updating the docs (website and readme) to clarify this.

May I suggest adding “with React” to the end of the “CSS-in-JS microlibrary for making design systems approachable” tagline?

The project’s scope may be extended in the future. I’m looking forward to introduce the concepts of glaze to other ecosystems.

**Comment by bnjm** [comment]
Sorry that I didn't get to this, but the changes look great. Much appreciated!

**Comment by kripod** [comment]
No worries, thank you for bringing my attention to this! 😊
