### ISSUE TITLE
Not working in Next.js

### ISSUE THREAD

**Issue by merelinguist** [kripod/glaze#6]
## Description

Trying to use the most minimal version of this, but is breaking with the error: `No treat theme provided`

## Reproduction

See this [Sandbox](https://codesandbox.io/s/next-glaze-no-treat-theme-provided-95vk9).

**Comment by kripod** [comment]
Thank you for reporting!

I've just created a [Next.js example project](https://github.com/kripod/glaze/tree/master/packages/example-nextjs), demonstrating the setup [as recommended by treat](https://seek-oss.github.io/treat/setup). Unfortunately, I couldn't manage to set up a Code Sandbox this time. A `treat.theme.{js,ts}` file is always required, and `createTheme from 'glaze'` shall be called exclusively from there to provide static style extraction.

A custom [Next plugin](https://github.com/zeit/next-plugins) could also be made for treat, removing boilerplate code from projects.

I would appreciate your feedback on the newly-made example project.

**Comment by merelinguist** [comment]
Looks great, thank you!
